### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kingalandydy** [oleksiy-nesterov/Avatar-Generator#1]
Hi Oleksiy,

It's a bit hard to work on this since we don't understand the architecture of the web app. Could you explain which files handle selection and rendering respectively? Also, why are there multiple copies of avatar-data.js?

**Comment by oleksiy-nesterov** [comment]
Hi. It will take some time to write documentation (and I don't sure that i want to do this). I just put code into GitHub as it is. Avatar-data.js file defines structure of all assets (i think, JSON is clear. This looks like:   gender/female/accessories/id/[color]/file) I don't see few copies of avatar-data.js in this repo...

I used Photoshop and JS to generate all assets and avatar-data.js file. Folder "assets" is technical folder. This folder do not need for the app, this is folder to store all graphic wich was used for the app.

![](https://api.monosnap.com/rpc/file/download?id=9Q2eTyAaY48A43mlRIFixZdfbt9Ski)

**Comment by kingalandydy** [comment]
Thank you for the information Oleksiy. Appreciate it.
